[package]
name = "surreal-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
serde = { version = "1.0.219", features = ["derive"]}
surrealdb = "2.2.1"
thiserror = "2.0.12"
